# Generated by Django 5.0.6 on 2024-11-04 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='課程名稱')),
                ('department', models.CharField(max_length=100, verbose_name='開課系所')),
                ('time', models.CharField(max_length=50, verbose_name='上課時間')),
                ('teacher', models.CharField(max_length=100, verbose_name='授課教師')),
                ('language', models.CharField(max_length=50, verbose_name='授課語言')),
                ('type', models.CharField(max_length=50, verbose_name='課程類型')),
            ],
            options={
                'verbose_name': '課程',
                'verbose_name_plural': '課程',
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course', verbose_name='課程')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student', verbose_name='學生')),
            ],
            options={
                'verbose_name': '課表',
                'verbose_name_plural': '課表',
                'unique_together': {('student_id', 'course_id')},
            },
        ),
    ]
